---
- hosts: centos
  user: sysadmin
  become: yes

  tasks:
    - name: Instalar NFS utils
      yum:
        name: nfs-utils
        state: present

    - name: Asegurar que el servicio NFS esté iniciado y habilitado
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Permitir puerto 2049/tcp en el firewall
      ansible.posix.firewalld:
        port: 2049/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Crear el directorio /var/nfs_shared con owner y permisos
      ansible.builtin.file:
        path: /var/nfs_shared
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'

    - name: Configurar exportación en /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: /var/nfs_shared  *(rw,sync,no_root_squash)
        create: yes
      notify: Recargar exports

  handlers:
    - name: Recargar exports
      command: exportfs -r
...
